apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - base/hspc-operator-namespace.yaml
  - base/regcred-redhat-io.yaml
  - base/regcred-redhat-com.yaml
  - base/hspc-operator.yaml
  - base/hspc_v1_hspc.yaml
  